### ISSUE TITLE
Use github releases

### ISSUE THREAD

**Issue by tracker1** [madushadhanushka/differ#1]
You should switch to github releases instead of dropbox.

Create a TAG and push the tag up to github.  This tag should match your built release... you can then upload release files associated with that tag.

This way you won't bump up against potential dropbox issues.

**Comment by madushadhanushka** [comment]
Application has been released with tag v0.1.0 https://github.com/madushadhanushka/differ/releases/tag/v0.1.0
- Linux https://github.com/madushadhanushka/differ/releases/download/v0.1.0/differ-linux_v0.1.0.zip
- Mac https://github.com/madushadhanushka/differ/releases/download/v0.1.0/differ-mac_v0.1.0.zip
- Windows https://github.com/madushadhanushka/differ/releases/download/v0.1.0/differ-win_v0.1.0.zip

Thank you for reporting.
